# Scala Steward configuration.
# See https://scala-steward.org/docs/configuration.html

scalafmt.runAfterUpgrade = true
commits.message = "[dependency] Updated ${artifactName} from ${currentVersion} to ${nextVersion}."
