// Configuration for Scalafmt, defining the canonical code style for this project.
// Use `sbt scalafmtAll` to reformat code, or `sbt scalafmtCheckAll` to check compliance.
// Ideally, you should enable "reformat-on-save" in your IDE.
// Full compliance is required before code can be merged.
// See: 'https://scalameta.org/scalafmt/'

version = 3.10.7
runner.dialect = scala3

maxColumn = 80
lineEndings = unix

// Comments

comments.indentTrailingInCaseBody = none

docstrings.style = SpaceAsterisk
docstrings.removeEmpty = true
docstrings.oneline = fold
docstrings.wrap = unfold
docstrings.blankFirstLine = unfold
docstrings.forceBlankLineBefore = true

// Spaces

spaces.beforeContextBoundColon = Always
spaces.withinContextBoundBraces = Never
spaces.inImportCurlyBraces = false
spaces.inInterpolatedStringCurlyBraces = true
spaces.inParentheses = false
spaces.aroundSymbolicInfixOperators = true
spaces.afterKeywordBeforeParen = true
spaces.inByNameTypes = true
spaces.afterSymbolicDefs = true
spaces.beforeApplyArgInParens = Never
spaces.beforeInfixArgInParens = Always
spaces.afterColonInMatchPattern = Always

// New lines

newlines.source = fold
newlines.beforeMultiline = fold
newlines.beforeTypeBounds = fold
newlines.beforeOpenParenDefnSite = unfold
newlines.afterCurlyLambdaParams = keep

newlines.sometimesBeforeColonInMethodReturnType = true
newlines.avoidInResultType = true
newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.forceBeforeMultilineAssign = never

newlines.implicitParamListModifierPrefer = before

newlines.topLevelBodyIfMinStatements = [before]
newlines.topLevelBodyMinStatements = 2

runner.optimizer.defnSite.minCount = 2
runner.optimizer.defnSite.minSpan = 40
runner.optimizer.callSite.minCount = 2
runner.optimizer.callSite.minSpan = 40

newlines.topLevelStatementBlankLines = [
  {
    minBreaks = 1
    blanks { before = 1, after = 0 }
  }
]

danglingParentheses {
  defnSite = true
  callSite = true
  ctrlSite = true
  importSite = true
}

newlines.selectChains.style = unfold
newlines.selectChains.enclose = true
newlines.selectChains.classicCanStartWithBraceApply = true
newlines.selectChains.classicCanStartWithoutApply = true

// Indentation

indent.main = 2
indent.callSite = 2
indent.defnSite = 2
indent.caseSite = 2
indent.extendSite = 2
indent.commaSiteRelativeToExtends = 8

indent.relativeToLhsLastLine = [match, infix]
indent.infix.exemptScope = all

align.preset = more
align.openParenCallSite = false
align.openParenCtrlSite = false
align.openParenDefnSite = false
align.stripMargin = false

// Literals

literals.long = Upper
literals.hexPrefix = Lower
literals.hexDigits = Upper
literals.binPrefix = Lower
literals.floatingPoint.float = Upper
literals.floatingPoint.double = Upper
literals.floatingPoint.scientific = Lower

// Rewrite rules

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  Imports,
  RemoveSemicolons,
  RewriteLiterals
]

rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.generalExpressions = true
rewrite.redundantBraces.ifElseExpressions = true
rewrite.redundantBraces.defnBodies = true
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantParens.infixSide = null

rewrite.imports.selectors = fold
rewrite.imports.sort = scalastyle
rewrite.imports.removeRedundantSelectors = true

rewrite.sortModifiers.preset = styleGuide

rewrite.trailingCommas.style = always

rewrite.tokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces {
  enabled = true
  oldSyntaxToo = true
  fewerBracesParensToo = true
  fewerBracesMinSpan = 2
}

// Build config files in 'project/' must be excluded from the requirement
// to use Scala 3 syntax, as sbt requires Scala 2 syntax.

fileOverride {
  "glob:**/project/**" {
    runner.dialect = scala213
    rewrite.scala3.convertToNewSyntax = false
    rewrite.scala3.removeOptionalBraces.enabled = false
  }
}
