package com.alecdorrington.scalgebra

import com.alecdorrington.scalgebra.evidence.collection.*
import com.alecdorrington.scalgebra.evidence.function.*
import com.alecdorrington.scalgebra.evidence.future.*
import com.alecdorrington.scalgebra.evidence.numeric.*
import com.alecdorrington.scalgebra.evidence.trivial.*
import com.alecdorrington.scalgebra.evidence.tuple.*

/**
  * The ultimate base trait of all Scalgebra type classes.
  *
  * This exists as a work-around for some idiosyncrasies of Scala's context
  * parameter resolution.
  *
  * In particular, all given instances are provided in [[Algebra]]'s companion
  * object, which allows them to always be found, even when not imported.
  */
trait Algebra[X]

/** The companion object for [[Algebra]]. */
object Algebra
  extends ArrayIsNormedAdditiveMonoid,
          ArraySeqIsNormedAdditiveMonoid,
          EitherIsAdditiveMonoid,
          IArrayIsNormedAdditiveMonoid,
          LazyListIsNormedAdditiveMonoid,
          ListIsNormedAdditiveMonoid,
          MapIsNormedAdditiveMonoid,
          OptionIsNormedAdditiveMonoid,
          OptionIsSemiring,
          QueueIsNormedAdditiveMonoid,
          SeqIsNormedAdditiveMonoid,
          SetIsLattice,
          SetIsNormedAdditiveMonoid,
          SortedMapIsNormedAdditiveMonoid,
          SortedSetIsLattice,
          SortedSetIsNormedAdditiveMonoid,
          StringIsNormedAdditiveMonoid,
          TryIsAdditiveMonoid,
          VectorIsNormedAdditiveMonoid,
          FunctionIsAdditiveGroup,
          FunctionIsAdditiveIdentity,
          FunctionIsAdditiveInverse,
          FunctionIsAdditiveMonoid,
          FunctionIsAdditiveSemigroup,
          FunctionIsBooleanAlgebra,
          FunctionIsBoundedJoinSemilattice,
          FunctionIsBoundedLattice,
          FunctionIsBoundedMeetSemilattice,
          FunctionIsDifference,
          FunctionIsDifferenceMonoid,
          FunctionIsDifferenceSemifield,
          FunctionIsDifferenceSemigroup,
          FunctionIsDifferenceSemiring,
          FunctionIsField,
          FunctionIsJoinSemilattice,
          FunctionIsLattice,
          FunctionIsMeetSemilattice,
          FunctionIsMultiplicativeGroup,
          FunctionIsMultiplicativeIdentity,
          FunctionIsMultiplicativeInverse,
          FunctionIsMultiplicativeMonoid,
          FunctionIsMultiplicativeSemigroup,
          FunctionIsPseudoring,
          FunctionIsQuotient,
          FunctionIsQuotientDifferenceSemiring,
          FunctionIsQuotientMonoid,
          FunctionIsQuotientRing,
          FunctionIsQuotientSemigroup,
          FunctionIsQuotientSemiring,
          FunctionIsRing,
          FunctionIsSemifield,
          FunctionIsSemiring,
          FutureIsAdditiveGroup,
          FutureIsAdditiveIdentity,
          FutureIsAdditiveInverse,
          FutureIsAdditiveMonoid,
          FutureIsAdditiveSemigroup,
          FutureIsDifference,
          FutureIsDifferenceMonoid,
          FutureIsDifferenceSemifield,
          FutureIsDifferenceSemigroup,
          FutureIsDifferenceSemiring,
          FutureIsField,
          FutureIsMultiplicativeGroup,
          FutureIsMultiplicativeIdentity,
          FutureIsMultiplicativeInverse,
          FutureIsMultiplicativeMonoid,
          FutureIsMultiplicativeSemigroup,
          FutureIsPseudoring,
          FutureIsQuotient,
          FutureIsQuotientDifferenceSemiring,
          FutureIsQuotientMonoid,
          FutureIsQuotientRing,
          FutureIsQuotientSemigroup,
          FutureIsQuotientSemiring,
          FutureIsRing,
          FutureIsSemifield,
          FutureIsSemiring,
          BigDecimalIsArchimedeanField,
          BigIntIsOrderedQuotientRing,
          BooleanIsBooleanAlgebra,
          BooleanIsOrderedSemifield,
          ByteIsOrderedQuotientRing,
          DoubleIsArchimedeanField,
          FloatIsArchimedeanField,
          FractionalIsOrderedField,
          IntIsOrderedQuotientRing,
          IntegralIsOrderedQuotientRing,
          LongIsOrderedQuotientRing,
          NumericIsOrderedRing,
          ShortIsOrderedQuotientRing,
          EmptyTupleIsOrderedRing,
          NoneIsOrderedRing,
          NothingIsIdentityFreeAlgebra,
          UnitIsOrderedRing,
          TupleIsAdditiveGroup,
          TupleIsAdditiveIdentity,
          TupleIsAdditiveInverse,
          TupleIsAdditiveMonoid,
          TupleIsAdditiveSemigroup,
          TupleIsDifference,
          TupleIsDifferenceMonoid,
          TupleIsDifferenceSemifield,
          TupleIsDifferenceSemigroup,
          TupleIsDifferenceSemiring,
          TupleIsField,
          TupleIsMultiplicativeGroup,
          TupleIsMultiplicativeIdentity,
          TupleIsMultiplicativeInverse,
          TupleIsMultiplicativeMonoid,
          TupleIsMultiplicativeSemigroup,
          TupleIsOrderedAdditiveGroup,
          TupleIsOrderedAdditiveIdentity,
          TupleIsOrderedAdditiveInverse,
          TupleIsOrderedAdditiveMonoid,
          TupleIsOrderedAdditiveSemigroup,
          TupleIsOrderedDifference,
          TupleIsOrderedDifferenceMonoid,
          TupleIsOrderedDifferenceSemifield,
          TupleIsOrderedDifferenceSemigroup,
          TupleIsOrderedDifferenceSemiring,
          TupleIsOrderedField,
          TupleIsOrderedMultiplicativeGroup,
          TupleIsOrderedMultiplicativeIdentity,
          TupleIsOrderedMultiplicativeInverse,
          TupleIsOrderedMultiplicativeMonoid,
          TupleIsOrderedMultiplicativeSemigroup,
          TupleIsOrderedPseudoring,
          TupleIsOrderedQuotient,
          TupleIsOrderedQuotientDifferenceSemiring,
          TupleIsOrderedQuotientMonoid,
          TupleIsOrderedQuotientRing,
          TupleIsOrderedQuotientSemigroup,
          TupleIsOrderedQuotientSemiring,
          TupleIsOrderedRing,
          TupleIsOrderedSemifield,
          TupleIsOrderedSemiring,
          TupleIsPseudoring,
          TupleIsQuotient,
          TupleIsQuotientDifferenceSemiring,
          TupleIsQuotientMonoid,
          TupleIsQuotientRing,
          TupleIsQuotientSemigroup,
          TupleIsQuotientSemiring,
          TupleIsRing,
          TupleIsSemifield,
          TupleIsSemiring
