package com.alecdorrington.scalgebra

import com.alecdorrington.scalgebra.evidence.collection.*
import com.alecdorrington.scalgebra.evidence.function.*
import com.alecdorrington.scalgebra.evidence.future.*
import com.alecdorrington.scalgebra.evidence.numeric.*
import com.alecdorrington.scalgebra.evidence.trivial.*
import com.alecdorrington.scalgebra.evidence.tuple.*

/**
  * The ultimate base trait of all Scalgebra type classes.
  *
  * This exists as a work-around for some idiosyncrasies of Scala's context
  * parameter resolution.
  *
  * In particular, all given instances are provided in [[Root]]'s companion
  * object, which allows them to always be found, even when not imported.
  */
trait Root[X]

/** The companion object for [[Root]]. */
object Root
  extends Root.Ops,
          ArrayIsNormedAdditiveMonoid,
          ArraySeqIsNormedAdditiveMonoid,
          EitherIsAdditiveMonoid,
          IArrayIsNormedAdditiveMonoid,
          LazyListIsNormedAdditiveMonoid,
          ListIsNormedAdditiveMonoid,
          MapIsNormedAdditiveMonoid,
          OptionIsNormedAdditiveMonoid,
          OptionIsSemiring,
          QueueIsNormedAdditiveMonoid,
          SeqIsNormedAdditiveMonoid,
          SetIsNormedAdditiveMonoid,
          SortedMapIsNormedAdditiveMonoid,
          SortedSetIsNormedAdditiveMonoid,
          StringIsNormedAdditiveMonoid,
          TryIsAdditiveMonoid,
          VectorIsNormedAdditiveMonoid,
          FunctionIsAdditiveGroup,
          FunctionIsAdditiveIdentity,
          FunctionIsAdditiveInverse,
          FunctionIsAdditiveMonoid,
          FunctionIsAdditiveSemigroup,
          FunctionIsDifference,
          FunctionIsDifferenceMonoid,
          FunctionIsDifferenceSemifield,
          FunctionIsDifferenceSemigroup,
          FunctionIsDifferenceSemiring,
          FunctionIsEuclidean,
          FunctionIsEuclideanMonoid,
          FunctionIsEuclideanRing,
          FunctionIsEuclideanSemigroup,
          FunctionIsField,
          FunctionIsMultiplicativeGroup,
          FunctionIsMultiplicativeIdentity,
          FunctionIsMultiplicativeInverse,
          FunctionIsMultiplicativeMonoid,
          FunctionIsMultiplicativeSemigroup,
          FunctionIsPseudoring,
          FunctionIsRing,
          FunctionIsSemifield,
          FunctionIsSemiring,
          FutureIsAdditiveGroup,
          FutureIsAdditiveIdentity,
          FutureIsAdditiveInverse,
          FutureIsAdditiveMonoid,
          FutureIsAdditiveSemigroup,
          FutureIsDifference,
          FutureIsDifferenceMonoid,
          FutureIsDifferenceSemifield,
          FutureIsDifferenceSemigroup,
          FutureIsDifferenceSemiring,
          FutureIsEuclidean,
          FutureIsEuclideanMonoid,
          FutureIsEuclideanRing,
          FutureIsEuclideanSemigroup,
          FutureIsField,
          FutureIsMultiplicativeGroup,
          FutureIsMultiplicativeIdentity,
          FutureIsMultiplicativeInverse,
          FutureIsMultiplicativeMonoid,
          FutureIsMultiplicativeSemigroup,
          FutureIsPseudoring,
          FutureIsRing,
          FutureIsSemifield,
          FutureIsSemiring,
          BigIntIsOrderedEuclideanRing,
          BooleanIsOrderedRing,
          ByteIsOrderedEuclideanRing,
          DoubleIsOrderedField,
          FloatIsOrderedField,
          FractionalIsOrderedField,
          IntIsOrderedEuclideanRing,
          IntegralIsOrderedEuclideanRing,
          LongIsOrderedEuclideanRing,
          NumericIsOrderedRing,
          ShortIsOrderedEuclideanRing,
          EmptyTupleIsOrderedField,
          NoneIsOrderedField,
          NothingIsOrderedField,
          SingletonIsOrderedField,
          UnitIsOrderedField,
          TupleIsAdditiveGroup,
          TupleIsAdditiveIdentity,
          TupleIsAdditiveInverse,
          TupleIsAdditiveMonoid,
          TupleIsAdditiveSemigroup,
          TupleIsDifference,
          TupleIsDifferenceMonoid,
          TupleIsDifferenceSemifield,
          TupleIsDifferenceSemigroup,
          TupleIsDifferenceSemiring,
          TupleIsEuclidean,
          TupleIsEuclideanMonoid,
          TupleIsEuclideanRing,
          TupleIsEuclideanSemigroup,
          TupleIsField,
          TupleIsMultiplicativeGroup,
          TupleIsMultiplicativeIdentity,
          TupleIsMultiplicativeInverse,
          TupleIsMultiplicativeMonoid,
          TupleIsMultiplicativeSemigroup,
          TupleIsOrderedAdditiveGroup,
          TupleIsOrderedAdditiveIdentity,
          TupleIsOrderedAdditiveInverse,
          TupleIsOrderedAdditiveMonoid,
          TupleIsOrderedAdditiveSemigroup,
          TupleIsOrderedDifference,
          TupleIsOrderedDifferenceMonoid,
          TupleIsOrderedDifferenceSemifield,
          TupleIsOrderedDifferenceSemigroup,
          TupleIsOrderedDifferenceSemiring,
          TupleIsOrderedEuclidean,
          TupleIsOrderedEuclideanMonoid,
          TupleIsOrderedEuclideanRing,
          TupleIsOrderedEuclideanSemigroup,
          TupleIsOrderedField,
          TupleIsOrderedMultiplicativeGroup,
          TupleIsOrderedMultiplicativeIdentity,
          TupleIsOrderedMultiplicativeInverse,
          TupleIsOrderedMultiplicativeMonoid,
          TupleIsOrderedMultiplicativeSemigroup,
          TupleIsOrderedPseudoring,
          TupleIsOrderedRing,
          TupleIsOrderedSemifield,
          TupleIsOrderedSemiring,
          TupleIsPseudoring,
          TupleIsRing,
          TupleIsSemifield,
          TupleIsSemiring:

  trait Ops

  export com.alecdorrington.scalgebra.Root

  /** The [[Root]] instance describing the current algebra system. */
  inline def root[X : Root as root]: Root[X] = root
